### ISSUE TITLE
html

### ISSUE THREAD

**Issue by Caaalabash** [Caaalabash/day-day-up#20]

**Comment by Caaalabash** [comment]
loading效果

````html
<svg class="circular" viewBox="25 25 50 50">
  <circle class="path" cx="50" cy="50" r="20" fill="none"/>
</svg>
````

````css
.circular {
    height: 42px;
    width: 42px;
    animation: loading-rotate 2s linear infinite
}
.path {
    animation: loading-dash 1.5s ease-in-out infinite;
    stroke-dasharray: 90, 150;
    stroke-dashoffset: 0;
    stroke-width: 2;
    stroke: #409eff;
    stroke-linecap: round
}
@keyframes loading-rotate {
    to {
        transform: rotate(1turn)
    }
}
@keyframes loading-dash {
    0% {
        stroke-dasharray: 1,200;
        stroke-dashoffset: 0
    }

    50% {
        stroke-dasharray: 90,150;
        stroke-dashoffset: -40px
    }

    to {
        stroke-dasharray: 90,150;
        stroke-dashoffset: -120px
    }
}
````

[效果：codepen - loading](https://codepen.io/caaalabash/pen/vYOXjyj)
